[build-system]
requires = [
    'setuptools >= 77.0.0',
]
build-backend = "setuptools.build_meta"

[project]
name = "passagemath-cell-server"
dependencies = [
    # from README.md
    'lockfile',
    'paramiko',
    'sockjs-tornado',
    'sqlalchemy',
    # passagemath
    'passagemath-repl',
    'passagemath-symbolics',
]
